### ISSUE TITLE
Automatically select default colors for highlighting

### ISSUE THREAD

**Issue by andrewhill157** [CSE512-15S/fp-tdurham-ajh24-chaisson-ningli30#18]
If I remember correctly, the people who evaluated our assignment 3 liked the ability to choose colors, but thought that it would also be good to have some reasonable defaults. Since we are limiting to four highlights, I would potentially recommend

```
#e41a1c
#377eb8
#4daf4a
#984ea3
```

Colorbrewer is also a good source of alternative color schemes if you are not a fan of those colors (click the qualitative radio button): http://colorbrewer2.org/

**Comment by andrewhill157** [comment]
This is done in 9c98a7c47ff32f87e7b656bc86321989b6ca0659. 

We should check that the default colors populate in the selector properly on everyone's setup, but the actual color cells get highlighted matches what I expect. The default color for cells is now grey rather than steelblue to allow blue to be used as a highlight color. We can change this behavior to something else if grey is too hard to see.

**Comment by andrewhill157** [comment]
If this looks good, I can close this issue.

**Comment by tdurham86** [comment]
I just fixed the default color display in the lineage picker. For some reason the color is properly displayed when the color value is changed in the template LPDiv before cloning instead of cloning the template and then changing the color value. Weird. To make sure that we don't ever have duplicate default colors, I changed the default colors data structure to be a javascript object mapping the color hex values to booleans indicating whether or not that default color is currently in use. This way lineage pickers can "check out" a default color and put it back when they are removed. Last thing to note is that I used the "defaultValue" attribute of the color input element to store these values in case the user changes the color during the life of the lineage picker (so we always know which default color to free up if a lineage picker is removed).

The small multiples plots now also correctly update to reflect the current lineage picker selections -- I added the small multiples points to the color/size updating callbacks when the lineage picker controls are changed.

We may still want to play with the default color selections, but for now I think it's fine to close this issue.
